---

# install base package ( packages needed for the installation process )
- name: Prepare installation
  apt: >
    name={{ item }}
    update_cache={{ update_apt_cache }}
    install_recommends=no
    state=latest
    cache_valid_time={{ cache_valid_time }}
  with_items:
    - curl
    - software-properties-common
    - python3-software-properties

  tags:
    - packages
    - splash

# add the qt repo
- name : Add qt551 repo
  apt_repository: >
    repo='ppa:beineri/opt-qt551-trusty'
    validate_certs=no
    update_cache=yes
# add the repo that contain some packages not in ubunt official repos example libre2.0 and libre2.0-dev
- name : Add pi-rho repo
  apt_repository: >
    repo='ppa:pi-rho/security'
    validate_certs=no
    update_cache=yes

# install deps
- name: Install dependencies
  apt: >
    name={{ item }}
    update_cache={{ update_apt_cache }}
    install_recommends=no
    state=latest
    cache_valid_time={{ cache_valid_time }}
  with_items:
    - netbase
    - ca-certificates
    - xvfb
    - pkg-config
    - python3
    - qt55base
    - qt55webkit
    - qt55svg
    - libre2
    - libicu52
    - liblua5.2-0
    - zlib1g
  tags:
    - packages
    - splash

# install build deps
- name: Install build depenendcies
  apt: >
    name={{ item }}
    update_cache={{ update_apt_cache }}
    install_recommends=no
    state=latest
    cache_valid_time={{ cache_valid_time }}
  with_items:
    - python3-dev
    - python3-pip
    - build-essential
    - libre2-dev
    - liblua5.2-dev
    - libsqlite3-dev
    - zlib1g-dev
    - libjpeg-turbo8-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - mesa-common-dev
  tags:
    - packages
    - splash

# create splash user and group
- include: create_users_and_groups.yml
  tags:
    - splash
    - virtualenv
    - qt5

- stat: path={{ splash_virtualenv_path }}/bin/activate
  register: virtualenv_actv_dir

# setup virtualenv
# Avoid re-creating virtualenv if it's already created
- include: setup_virtualenv.yml
  when: virtualenv_actv_dir.stat.exists == False
  tags:
    - splash
    - virtualenv
    - qt5

- stat: path={{ splash_virtualenv_path }}/lib/python3.4/site-packages/PyQt5/
  register: qt_module_dir

# install qt5
# Avoid re-installing qt5 if it's already installed and compiled 
- include: install_qt5.yml
  when: qt_module_dir.stat.exists == False
  tags:
    - splash
    - qt5

# install python dependencies
# Here we use shell instead of the ansible pip wrapper because of the problem related to python3 pip and virtualenv
- name: install lupa
  shell: /bin/bash -c "source {{ splash_virtualenv_path}}/bin/activate && pip3 install qt5reactor==0.3 psutil==3.4.2 Twisted==15.5.0 adblockparser==0.5 xvfbwrapper==0.2.5 funcparserlib==0.3.6 Pillow==3.1.1 cython==0.23.4"

- name: install lupa
  shell: /bin/bash -c "source {{ splash_virtualenv_path}}/bin/activate && pip3 install --install-option="--with-cython" https://github.com/scoder/lupa/archive/8c74d0a278b45df5d813abbab64377e80864bd56.zip#egg=lupa"
  tags:
    - splash
    - lupa

- name: install splash
  shell: /bin/bash -c "source {{ splash_virtualenv_path}}/bin/activate && pip3 install six==1.10.0 splash==2.0.3"
  tags:
    - splash

# create lua modules directory
- name: Create splash lua modules directory
  file: path={{ splash_lua_modules_path }} state=directory owner={{ splash_user }} group={{ splash_group }} mode=0775
  tags:
    - splash
    - qt5


# create proxy profile directory
- name: Create splash proxy profiles directory
  file: path={{ splash_proxy_profile_path }} state=directory owner={{ splash_user }} group={{ splash_group }} mode=0775
  tags:
    - splash
    - qt5

# create js profile directory
- name: Create splash js profiles directory
  file: path={{ splash_js_profiles_path }} state=directory owner={{ splash_user }} group={{ splash_group }} mode=0775
  tags:
    - splash
    - qt5

# create log directory
- name: Create splash log directory
  file: path={{ splash_log_dir }} state=directory owner={{ splash_user }} group={{ splash_group }} mode=0775
  tags:
    - splash
    - qt5

- include: setup_supervisor.yml
  tags:
    - splash
    - supervisor




